name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      REPOSITORY_NAME: car_comparison
      CLUSTER_NAME: car_cluster
      SERVICE_NAME: car_service

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker registry
        run: echo ${{ secrets.AWS_ECR_PASSWORD }} | docker login -u AWS --password-stdin ${{ secrets.AWS_ECR_REGISTRY }}

      - name: Build Docker image
        run: docker build -t your-image-name .

      - name: Tag Docker image
        run: docker tag your-image-name:latest ${{ secrets.AWS_ECR_REGISTRY }}/$REPOSITORY_NAME:latest

      - name: Push Docker image to ECR
        run: docker push ${{ secrets.AWS_ECR_REGISTRY }}/$REPOSITORY_NAME:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
